language: go

go:
  - 1.5
#  - 1.6
install:
# Add Godeps dependencies to GOPATH and PATH
#  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
#  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - go get github.com/tools/godep
  - godep restore
  - go get -t -v ./...

#  - go get github.com/dorzheh/deployer
#  - go get github.com/dorzheh/infra
#env:
#  #matrix:
#  - OS_TYPE=opensuse OS_VERSION=13.2 ANSIBLE_VERSION=1.9.2

branches:
  only:
  - master
#  - stable

#services:
#  - docker
#script: go test ./...
script:
  - go build  example/myproduct/deployer/deployer.go


notifications:
  email: false
#  hipchat:
#    rooms:
